# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excel2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

from src.Pyqt_test import BaseExcel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(623, 402)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 277, 372))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.file_path = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.file_path.setObjectName("file_path")
        self._5 = QtWidgets.QHBoxLayout(self.file_path)
        self._5.setObjectName("_5")
        self.label_4 = QtWidgets.QLabel(self.file_path)
        self.label_4.setObjectName("label_4")
        self._5.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.file_path)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self._5.addWidget(self.lineEdit_4)
        self.verticalLayout.addWidget(self.file_path)
        self.sheetname = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.sheetname.setObjectName("sheetname")
        self._4 = QtWidgets.QHBoxLayout(self.sheetname)
        self._4.setObjectName("_4")
        self.label_5 = QtWidgets.QLabel(self.sheetname)
        self.label_5.setObjectName("label_5")
        self._4.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.sheetname)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self._4.addWidget(self.lineEdit_5)
        self.verticalLayout.addWidget(self.sheetname)
        self.button1 = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setObjectName("button1")
        self._3 = QtWidgets.QHBoxLayout(self.button1)
        self._3.setObjectName("_3")
        self.checkboxlist = QtWidgets.QWidget(self.button1)
        self.checkboxlist.setObjectName("checkboxlist")
        self._2 = QtWidgets.QVBoxLayout(self.checkboxlist)
        self._2.setObjectName("_2")
        self.checkBox = QtWidgets.QCheckBox(self.checkboxlist)
        self.checkBox.setObjectName("checkBox")
        self._2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.checkboxlist)
        self.checkBox_2.setObjectName("checkBox_2")
        self._2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.checkboxlist)
        self.checkBox_3.setObjectName("checkBox_3")
        self._2.addWidget(self.checkBox_3)
        self._3.addWidget(self.checkboxlist)
        self.verticalLayout.addWidget(self.button1)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.keyword = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.keyword.setObjectName("keyword")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.keyword)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.keyword)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.keyword)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_4 = QtWidgets.QPushButton(self.keyword)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_2.addWidget(self.keyword)
        self.data = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.data.setObjectName("data")
        self.datatext = QtWidgets.QHBoxLayout(self.data)
        self.datatext.setContentsMargins(1, 1, 1, 1)
        self.datatext.setObjectName("datatext")
        self.label_3 = QtWidgets.QLabel(self.data)
        self.label_3.setObjectName("label_3")
        self.datatext.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.data)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.datatext.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addWidget(self.data)
        self.horizontalWidget_4 = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalWidget_4)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_8.addWidget(self.spinBox)
        self.label_7 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.spinBox_2 = QtWidgets.QSpinBox(self.horizontalWidget_4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_8.addWidget(self.spinBox_2)
        self.verticalLayout_2.addWidget(self.horizontalWidget_4)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayout_2.addWidget(self.horizontalWidget_3)
        self.verticalLayout.addWidget(self.verticalGroupBox_2)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(310, 20, 291, 371))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.show_path)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "文件路径"))
        self.label_5.setText(_translate("Form", "工作簿名"))
        self.checkBox.setText(_translate("Form", "只读"))
        self.checkBox_2.setText(_translate("Form", "纯数据模式"))
        self.checkBox_3.setText(_translate("Form", "超链接保持模式"))
        self.label.setText(_translate("Form", "关键字"))
        self.pushButton_4.setText(_translate("Form", "读取位置"))
        self.label_3.setText(_translate("Form", "输入文字"))
        self.label_6.setText(_translate("Form", "最大列数"))
        self.label_7.setText(_translate("Form", "最大行数"))
        self.pushButton.setText(_translate("Form", "按列刷取"))
        self.pushButton_2.setText(_translate("Form", "按行刷取"))
        self.pushButton_5.setText(_translate("Form", "混合刷取"))

    def text_edit_init(self):
        self.lineEdit_4.textChanged.connect(self.show_text_func)  # 1

    def show_text_func(self):
        self.textBrowser.setText(self.lineEdit_4.text())  # 2

    def show_path(self):
        path = self.lineEdit_4.text()
        sheet_name = self.lineEdit_5.text()
        keyword = self.lineEdit.text()
        data1 = self.lineEdit_3.text()
        self.textBrowser.append(path)
        self.textBrowser.append(sheet_name)
        self.textBrowser.append(keyword)
        self.textBrowser.append(data1)
        BaseExcel(path, sheet_name).enter_data_by_vertical(keyword, data1)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
