# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excel1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(656, 424)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(69)
        sizePolicy.setVerticalStretch(68)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        # Dialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setBaseSize(QtCore.QSize(315, 186))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.file_path = QtWidgets.QWidget(self.widget_2)
        self.file_path.setObjectName("file_path")
        self._5 = QtWidgets.QHBoxLayout(self.file_path)
        self._5.setObjectName("_5")
        self.label_4 = QtWidgets.QLabel(self.file_path)
        self.label_4.setObjectName("label_4")
        self._5.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.file_path)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self._5.addWidget(self.lineEdit_4)
        self.verticalLayout.addWidget(self.file_path)
        self.sheetname = QtWidgets.QWidget(self.widget_2)
        self.sheetname.setObjectName("sheetname")
        self._4 = QtWidgets.QHBoxLayout(self.sheetname)
        self._4.setObjectName("_4")
        self.label_5 = QtWidgets.QLabel(self.sheetname)
        self.label_5.setObjectName("label_5")
        self._4.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.sheetname)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self._4.addWidget(self.lineEdit_5)
        self.verticalLayout.addWidget(self.sheetname)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.button1 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setObjectName("button1")
        self._3 = QtWidgets.QHBoxLayout(self.button1)
        self._3.setObjectName("_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.button1)
        self.pushButton_3.setObjectName("pushButton_3")
        self._3.addWidget(self.pushButton_3)
        self.checkboxlist = QtWidgets.QWidget(self.button1)
        self.checkboxlist.setObjectName("checkboxlist")
        self._2 = QtWidgets.QVBoxLayout(self.checkboxlist)
        self._2.setObjectName("_2")
        self.checkBox = QtWidgets.QCheckBox(self.checkboxlist)
        self.checkBox.setObjectName("checkBox")
        self._2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.checkboxlist)
        self.checkBox_2.setObjectName("checkBox_2")
        self._2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.checkboxlist)
        self.checkBox_3.setObjectName("checkBox_3")
        self._2.addWidget(self.checkBox_3)
        self._3.addWidget(self.checkboxlist)
        self.verticalLayout_5.addWidget(self.button1)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.keyword = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.keyword.setObjectName("keyword")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.keyword)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.keyword)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.keyword)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_4 = QtWidgets.QPushButton(self.keyword)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_2.addWidget(self.keyword)
        self.data = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.data.setObjectName("data")
        self.datatext = QtWidgets.QHBoxLayout(self.data)
        self.datatext.setContentsMargins(1, 1, 1, 1)
        self.datatext.setObjectName("datatext")
        self.label_3 = QtWidgets.QLabel(self.data)
        self.label_3.setObjectName("label_3")
        self.datatext.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.data)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.datatext.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addWidget(self.data)
        self.horizontalWidget_4 = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalWidget_4)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_8.addWidget(self.spinBox)
        self.label_7 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.spinBox_2 = QtWidgets.QSpinBox(self.horizontalWidget_4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_8.addWidget(self.spinBox_2)
        self.verticalLayout_2.addWidget(self.horizontalWidget_4)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayout_2.addWidget(self.horizontalWidget_3)
        self.verticalLayout_5.addWidget(self.verticalGroupBox_2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setMinimumSize(QtCore.QSize(320, 400))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "文件路径"))
        self.label_5.setText(_translate("Dialog", "工作簿名"))
        self.pushButton_3.setText(_translate("Dialog", "openpyxl开启"))
        self.checkBox.setText(_translate("Dialog", "只读"))
        self.checkBox_2.setText(_translate("Dialog", "纯数据模式"))
        self.checkBox_3.setText(_translate("Dialog", "超链接保持模式"))
        self.label.setText(_translate("Dialog", "关键字"))
        self.pushButton_4.setText(_translate("Dialog", "读取位置"))
        self.label_3.setText(_translate("Dialog", "输入文字"))
        self.label_6.setText(_translate("Dialog", "最大列数"))
        self.label_7.setText(_translate("Dialog", "最大行数"))
        self.pushButton.setText(_translate("Dialog", "按列刷取"))
        self.pushButton_2.setText(_translate("Dialog", "按行刷取"))
        self.pushButton_5.setText(_translate("Dialog", "混合刷取"))

